name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0

      - name: Fetch NPM dependencies
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH=$HOME/.npm-global/bin:$PATH
          npm install -g @babel/cli @babel/core
          yarn

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - name: Build Site
        run: hugo --minify

      - uses: actions/checkout@master
      - name: Deploy
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./public
          remote: /var/lib/liputenpo/site
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
