name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0

      - name: Fetch NPM dependencies
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH=$HOME/.npm-global/bin:$PATH
          npm install -g @babel/cli @babel/core
          yarn

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - uses: actions/checkout@v2
        name: Checkout Current Site
        with:
          repository: 'lipukule/lipukule.github.io'
          submodules: false
          fetch-depth: 0
          path: './public/'

      - name: Update Site
        run: hugo --minify

      - uses: EndBug/add-and-commit@v7
        name: Deploy Site
        with:
          message: 'Deploy ste'
          add: '--all'
          cwd: './public/'